- name: Install statsd from GitHub
  shell: "git clone https://github.com/etsy/statsd.git /opt/statsd"
  sudo: true

- name: Configure statsd
  template: src=localConfig.js.j2 dest=/opt/statsd/localConfig.js

- name: Copy supervisor configuration for statsd
  template: src=supervisor-statsd.conf.j2 dest=/etc/supervisor/conf.d/statsd.conf
  notify: 
    - reload supervisor
