- name: Install epel-release
  yum: pkg=epel-release

# @development is a groupinstall, see https://coderwall.com/p/k6goya
- name: install common packages for redhat/centos
  yum: pkg={{ item }} state=latest
  with_items:
    - '@development'
    - git
    - libselinux-python
  when: ansible_os_family == "RedHat"

